defaults: &defaults
  twitter:
    app_id:           2578005
    consumer_key:     7XFrl1DsveghtKGdvwWrpw
    consumer_secret:  PUMFOKANJYk8he9Ii2a0lxD61T8ncv6BCVjfM9sBY


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
