defaults: &defaults
  twitter:
    app_id:           <YOUR-TWITTER-APP-ID>
    consumer_key:     <YOUR-TWITTER-APP-CONSUMER-KEY>
    consumer_secret:  <YOUR-TWITTER-APP-CONSUMER-SECRET>
  facebook:
    app_id:           <YOUR-FACEBOOK-APP-ID>
    consumer_key:     <YOUR-FACEBOOK-APP-CONSUMER-KEY>
    consumer_secret:  <YOUR-FACEBOOK-APP-CONSUMER-SECRET>
  linkedin:
    app_id:           <YOUR-LINKEDIN-APP-ID>
    consumer_key:     <YOUR-LINKEDIN-APP-CONSUMER-KEY>
    consumer_secret:  <YOUR-LINKEDIN-APP-CONSUMER-SECRET>


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
